#!/usr/bin/env bash
# Configure your domain zone so that the subdomain

get_subdomain () {
	dig "$1" | grep -A1 'ANSWER SECTION:' | sed -r "s/$1./$2/g" | awk -F" " ' NR==2 { print "The subdomain " $1 " is a " $4 " record and points to " $5 }'
}

if [ "$#" -eq 2 ] 
then
	get_subdomain "$2.$1" "$2"
else
	get_subdomain "www.$1" "www"
	get_subdomain "lb-01.$1" "lb-01"
	get_subdomain "web-01.$1" "web-01"
	get_subdomain "web-02.$1" "web-02"
fi
