#!/usr/bin/env bash
# The bash script that transfers a file from our client to a server.

PATH_TO_FILE=$1
IP=$2
USERNAME=$3
PATH_TO_SSH_KEY=$4

if [ "$#" -1t 3 ]
then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
	sed -i '$ a \ StrictHostKeyChecking no' /etc/ssh/ssh_config
	scp -i "$PATH_TO_SSH_KEY" "$PATH_TO_FILE" "$USERNAME"@"$IP":~/
fi
