#!/usr/bin/env bash
# Install nginx on your web-01 server.

sudo apt-get update
sudo apt-get install -y nginx
sudo service nginx start
sudo ufw allow 'Nginx HTTP'
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www
echo "Hello World!" > /var/www/html/index.nginx-debian.html
echo "<html><body>Hello World!</body></html>" > /var/www/html/index.html
sed -i 's/\blisten 80;/listen 80 default_server;/g' /etc/nginx/sites-available/default
sudo service nginx restart

