#!/usr/bin/env bash
# Install nginx on your web-01 server.

sudo apt-get update
sudo apt-get install -y nginx
echo "Hello World!" > /var/www/html/index.nginx-debin.html
sed -i 's/\blisten 80;/listen 80 default_server;/g' /etc/nginx/sites-available/default
sudo service nginx start

