#!/usr/bin/env bash
# Install nginx on your web-01 server.

apt-get update
apt-get install -y nginx

# Configure Nginx to listen on port 80 and return "Hello World!"
echo "server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;

    server_name _;

    location / {
        return 200 'Hello World!';
        add_header Content-Type text/plain;
    }
}" > /etc/nginx/sites-available/default

# Restart Nginx
service nginx restart


