#!/usr/bin/env bash
# A script to configure your Nginx server so that /redirect_me redirects to another page.

ADD301_REDIRECT="\\\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;"

sudo apt-get update
sudo apt-get install -y nginx
sudo chown -R ubuntu /var/www
echo "Hello World!" > /var/www/html/index.nginx-debian.html

# Use sed to insert the redirection rule after the "server_name" directive
sudo sed -i '/server_name _;/a\\t'"$ADD301_REDIRECT" /etc/nginx/sites-available/default

sudo service nginx restart

