#!/usr/bin/env bash
# A script to configure your Nginx server so that /redirect_me redirects to another page.

# Update package lists and install Nginx
sudo apt-get update
sudo apt-get install -y nginx

# Create a basic HTML file
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html

# Define the string for replacement
string_for_replacement='\
        server_name _;\
        rewrite ^\/redirect_me https:\/\/github.com\/santaETH permanent;\
        '

# Use sed to replace the server configuration
sudo sed -i "/server_name _;/c\\$string_for_replacement" /etc/nginx/sites-enabled/default

# Restart Nginx to apply changes
if [ "$(pgrep -c nginx)" -le 0]; then
	sudo service nginx start
else
	sudo servic nginx restart
fi


