#!/usr/bin/env bash
# Customising a 404 error page

string_for_replacement="server_name _;\n\trewrite ^\/redirect_me https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4 permanent;"

sudo apt-get update
sudo apt-get install -y nginx
sudo chown -R ubuntu /var/www
echo "Hello World!" > /var/www/html/index.nginx-debian.html

sudo sed -i 's/server_name _;/'"$string_for_replacement/"'/g' /etc/nginx/sites-enabled/default

echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

string_for_replacement='listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\troot \/var/www/html;\n\n\t\tinternal;\n\t}'

sudo sed -i 's/listen 80 default_server;/'"$string_for_replacement/"'/g' /etc/nginx/sites-enabled/default

sudo service nginx restart

