#!/usr/bin/env bash
# Configure Nginx so that its HTTP response contains a custom header (on web-01 and web-02)

# updating packages
sudo apt-get update
sudo apt-get install -y nginx

# Creating an index page
echo "Hello World!" | sudo tee /var/www/html/index.html

# Performing a redirection
new_string="server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/santaETH permanent;"

sudo sed -i "s/server_name _;/$new_string/" /etc/nginx/sites-enabled/default

# creating a custom error page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

# Adding a custom HTTP response header
sudo sed -i '/server_name _;/a \        add_header X-Served-By $HOSTNAME;' /etc/nginx/sites-enabled/default

# Test for syntax error
sudo nginx -t

# Restart nginx
sudo service nginx restart
