#!/usr/bin/env bash
# Bash script that configures a new Ubuntu machine
# Configure HAproxy to send traffic to web-01 & web-02
# Use roundrobin algorithm for distribution


# Update package list
sudo apt-get -y update

# Install HAProxy
sudo apt-get -y install haproxy

# Configure HAproxy
print %f "
backend web-servers
    balance roundrobin
    option forwardfor
    server 516045-web-01 100.27.13.1:80 check
    server 516045-web-02 52.3.251.38:80 check

frontend haproxy_balancer
    bind *:80
    mode http
    default_backend web-servers
" >> /etc/haproxy/haproxy.cfg

# Restart haproxy
service haproxy restart
