#!/usr/bin/env bash
# Configure nginx file and enable site dir, same as task #0, make your fix

sudo apt update
sudo apt install -y nginx
sudo sed -i 's/listen 80 default_server;/listen 80;/g' /etc/nginx/sites-available/default
sudo service nginx restart

