#!/usr/bin/env bash

# Configure nginx file and enable site directory.
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default || true

# Restart nginx
sudo service nginx restart || true

# Kill the first Nginx process
kill "$(pgrep 'nginx' | head -n 1)" || true
